name: Bazarr
on:
  push:
    branches:
    - main
    paths:
    - bazarr/Dockerfile
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  bazarr:
    uses: ./.github/workflows/common.yml
    with:
      app: bazarr
      url: https://api.github.com/repos/morpheus65535/bazarr/releases/latest
      event: ${{ github.event_name }}
