name: Bazarr

on:
  push:
    branches:
    - main
    paths:
    - bazarr/Dockerfile
  schedule:
    - cron: "34 12 * * *"
  workflow_dispatch:

jobs:
  bazarr:
    uses: ./.github/workflows/main.yml
    permissions:
      contents: write
      packages: write
    with:
      app: bazarr
      url: https://api.github.com/repos/morpheus65535/bazarr/releases/latest
      event: ${{ github.event_name }}
