name: Main

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Release
        id: release
        run: echo release=$(cat ${{ inputs.app }}/release) >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
          flavor: latest=true
          tags: |
            # set latest tag for master branch
            type=raw,value=${{ steps.release.outputs.release }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ inputs.app }}/Dockerfile
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.app }}
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
