name: Prowlarr

on:
  push:
    branches:
    - main
    paths:
    - prowlarr/Dockerfile
  workflow_dispatch:

jobs:
  call-main-workflow:
    uses: ./.github/workflows/main.yml
    permissions:
      contents: read
      packages: write
    with:
      app: prowlarr

