name: Prowlarr

on:
  push:
    branches:
    - main
    paths:
    - prowlarr/Dockerfile
  schedule:
    - cron: "34 12 * * *"
  workflow_dispatch:

jobs:
  call-main-workflow:
    uses: ./.github/workflows/main.yml
    permissions:
      contents: write
      packages: write
    with:
      app: prowlarr
      url: https://api.github.com/repos/prowlarr/prowlarr/releases/latest
      event: ${{ github.event_name }}
