name: Prowlarr
on:
  push:
    branches:
    - main
    paths:
    - prowlarr/Dockerfile
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  prowlarr:
    uses: ./.github/workflows/common.yml
    with:
      app: prowlarr
      url: https://api.github.com/repos/Prowlarr/Prowlarr/releases/latest
      event: ${{ github.event_name }}
