name: Radarr
on:
  push:
    branches:
    - main
    paths:
    - radarr/Dockerfile
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  radarr:
    uses: ./.github/workflows/common.yml
    with:
      app: radarr
      url: https://api.github.com/repos/Radarr/Radarr/releases/latest
      event: ${{ github.event_name }}
