name: Radarr

on:
  push:
    branches:
    - main
    paths:
    - radarr/Dockerfile
  schedule:
    - cron: "34 12 * * *"
  workflow_dispatch:

jobs:
  radarr:
    uses: ./.github/workflows/main.yml
    permissions:
      contents: write
      packages: write
    with:
      app: radarr
      url: https://api.github.com/repos/Radarr/Radarr/releases/latest
      event: ${{ github.event_name }}
