name: Sonarr
on:
  push:
    branches:
    - main
    paths:
    - sonarr/Dockerfile
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  sonarr:
    uses: ./.github/workflows/common.yml
    with:
      app: sonarr
      url: https://api.github.com/repos/Sonarr/Sonarr/releases/latest
      event: ${{ github.event_name }}
