name: Sonarr

on:
  push:
    branches:
    - main
    paths:
    - sonarr/Dockerfile
  schedule:
    - cron: "34 12 * * *"
  workflow_dispatch:

jobs:
  sonarr:
    uses: ./.github/workflows/main.yml
    permissions:
      contents: write
      packages: write
    with:
      app: sonarr
      url: https://api.github.com/repos/Sonarr/Sonarr/releases/latest
      event: ${{ github.event_name }}
